### ISSUE TITLE
Weight Axis variable font

### ISSUE THREAD

**Issue by pichotta** [itfoundry/hind#7]
@lianghai 
manushiparikh

Hello Manushi and Liang,

The Google fonts team would love to see a variable fonts version of ‘**Hind**'. They have commissioned us @TypeNetwork to work on upgrading a number of font projects to be variable fonts with a single weight axis. The Hind family is one of several fonts from the Indian Type Foundry.

In order to achieve the highest quality and most efficient long term results we will be converting any original source data to UFO, if they are not UFOs already. The source data will be generated in the RoboFont environment using fontmake and ttfautohint. There has been progress on tools to make an easy path to move between the Glyphs and Robofont environment.

During the process we will be looking to improve any errors while preserving how the font appears and renders on different platforms.

It looks that the outlines in the UFO sources in this family are currently approximately 84% compatible.

We will start by making a fork off of this git repository. It is estimated that the upgrade will be completed for you in the next few months. When the proposed final font is approved by Google will you accept a pull request?

To confirm, are the **.ufo source files** on this git repository the most current and best data?
Hind_0.ufo   (is this equivalent to the Light style being served?)
Hind_1.ufo  (is this the Bold?)

We hope this answers some of your questions about the process. Please let us know if you have any additional comments.

Best Regards,

Jill Pichotta
Vice President
Type Network
pichotta@typenetwork.com

**Comment by pichotta** [comment]
On Nov 7, 2019, at 10:08 AM, Dave Crossland <dcrossland@google.com> wrote:

Hi Satya

TypeNetwork will be working on VF upgrades for me, on many families for efficiency, including some of yours. Please collaborate :)

Cheers
Dave

**Comment by pichotta** [comment]
@lianghai
@davelab6

Hello Satya,

As you know the Google fonts team would love to see variable fonts for the type families by 'Indian Type Foundry'. They have commissioned us @TypeNetwork to work on upgrading a number of font projects to be variable fonts with a single weight axis.

We will be working on these families in the coming weeks:
Hind
Hind Siliguri
Poppins
Rajdhani
Teko

We may also continue the project next year with these families:
Hind Guntur
Hind Vadodara
Kalam

The first posting on this thread gives some information about the process. We look forward to your reply so we know that you have received this letter. Please inform us of the best git address and contributor to collaborate with at ITF.

Thank you,

Jill Pichotta
@pichotta

**Comment by pichotta** [comment]
The work on the weight axis variable font for Hind Siliguri has been paused.

**Comment by mon-jai** [comment]
@pichotta Any updates?
